name: Build and Push to Docker Hub

on:
  workflow_run:
    workflows: [ "Lint And Check" ]
    types:
      - completed
  push:
    paths-ignore:
      - 'demonstration/**'
      - 'apps/frontend/**'

jobs:
  check-if-build-should-run:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    outputs:
      should_build: ${{ steps.filter.outputs.only_ignored == 'false' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check if only ignored files were changed
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            only_ignored:
              - 'demonstration/**'
              - 'apps/frontend/**'
          base: ${{ github.event.workflow_run.head_commit.id }}

  build-and-push-backend:
    runs-on: ubuntu-latest
    needs: check-if-build-should-run
    if: ${{ needs.check-if-build-should-run.outputs.should_build == 'true' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./apps/backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.IMAGE_NAME }}:${{ secrets.IMAGE_VERSION }}


  deploy-to-render:
    runs-on: ubuntu-latest
    needs: build-and-push-backend

    steps:
      - name: Trigger Render deploy
        uses: JorgeLNJunior/render-deploy@v1.4.5
        with:
          service_id: ${{ secrets.RENDER_SERVICE_ID }}
          api_key: ${{ secrets.RENDER_API_KEY }}
          wait_deploy: true
          github_token: ''

